### ISSUE TITLE
For a fresh package with no GitHub history, generator exits with "branch not found"

### ISSUE THREAD

**Issue by chiubaka** [chiubaka/generator-chiubaka-typescript-package#107]
```
Error chiubaka-typescript-package 

Branch not found
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/Users/dchiu/.nvm/versions/node/v16.15.1/lib/node_modules/generator-chiubaka-typescript-package/node_modules/@octokit/request-error/dist-node/index.js:57:21)
    at onError (/Users/dchiu/.nvm/versions/node/v16.15.1/lib/node_modules/yo/lib/cli.js:123:22)
    at /Users/dchiu/.nvm/versions/node/v16.15.1/lib/node_modules/yo/lib/cli.js:171:48
```

Likely while trying to update the GitHub repo settings. Some of these settings cannot / should not be changed until after the first push.

**Comment by chiubaka** [comment]
Current workaround is to add a dummy file to the GitHub repo then run the generator, then force push the changes onto the master branch.
